chore: update release workflow

diff --git a/.github/workflows/gh-release.yml b/.github/workflows/gh-release.yml
--- a/.github/workflows/gh-release.yml
+++ b/.github/workflows/gh-release.yml
@@ -15,7 +15,7 @@ on:
   workflow_call:
     inputs:
       branch_name:
-        description: "Default beach name for the GitHub Release"
+        description: "Default branch name for the GitHub Release"
         default: "main"
         required: false
         type: string
@@ -36,7 +36,7 @@ jobs:
       should_run: ${{ steps.should_run.outputs.should_run }}
     steps:
       - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
-      - name: "[DEBUG] Print latest commit"
+      - name: "Debug: Print latest commit"
         run: |
           echo ${{ github.sha }}
           echo $(git rev-list  --after="1 week" --max-count=1  ${{ github.sha }})
@@ -56,12 +56,14 @@ jobs:
 
   # STEP 2: Print the should_run output for debugging
   echo_should_run:
+    name: "Debug: Print should_run output"
     runs-on: ubuntu-latest
     needs: check_date
     steps:
-      - name: "[DEBUG] Print should_run output"
+      - name: "Print should_run output"
         run: |
           echo "## Should Run Status" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
           echo "Should Run - ${{ needs.check_date.outputs.should_run }}" >> $GITHUB_STEP_SUMMARY
           if [[ ${{ needs.check_date.outputs.should_run }} == "false" ]] ; then
             echo '❌ No fresh commits detected. Skipping the build process!' >> $GITHUB_STEP_SUMMARY
@@ -72,6 +74,7 @@ jobs:
   # STEP 3: Build the project if a fresh commit is available
   build:
     name: "Build: Node 20"
+    needs: check_date
     if: ${{ needs.check_date.outputs.should_run != 'false' }}
     runs-on: ubuntu-latest
     timeout-minutes: 10
@@ -101,6 +104,7 @@ jobs:
       tag: ${{ steps.changelog.outputs.tag }}
       clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
       version: ${{ steps.changelog.outputs.version }}
+      git_pr_branch: ${{ steps.branchname.outputs.git_pr_branch }}
 
     env:
       PR_BRANCH: release/ci-${{ github.sha }}
@@ -110,6 +114,12 @@ jobs:
         uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
         with:
           fetch-depth: 0
+
+      - name: Get the branch name
+        id: branchname
+        run: |
+          echo "git_pr_branch=${{ env.PR_BRANCH }}" >> $GITHUB_OUTPUT
+
       - name: Create release branch
         run: |
           git checkout -b ${{ env.PR_BRANCH }}
@@ -128,7 +138,24 @@ jobs:
       - name: Create Changelog PR with release notes
         if: steps.changelog.outputs.skipped == 'false'
         run: |
-          gh pr create --base ${{ inputs.branch_name }} --head ${{ env.PR_BRANCH }} --title 'release: ${{ steps.changelog.outputs.tag }} [skip-ci]' --body '${{ steps.changelog.outputs.clean_changelog }}'
+          PR_TITLE="release: ${{ steps.changelog.outputs.tag }} [skip-ci]"
+          PR_BODY="
+          ## Type of change
+          - [ ] Bug fix
+          - [ ] New feature (non-breaking change)
+          - [ ] Tech debt (refactoring, code cleanup, etc.)
+          - [ ] Build/deploy pipeline (CI/CD)
+          - [x] Other
+
+          ## Objective
+          Automated version bump to ${{ steps.changelog.outputs.tag }} by GitHub Actions."
+          CREATED_PR=$(gh pr create \
+            --base '${{ inputs.branch_name }}' \
+            --head '${{ env.PR_BRANCH }}' \
+            --title "$PR_TITLE" \
+            --body "$PR_BODY" \
+            --label 'ignore-for-release')
+          echo "Created PR: ${CREATED_PR}" >> $GITHUB_STEP_SUMMARY
         env:
           GH_TOKEN: ${{ github.token }}
 
@@ -141,14 +168,23 @@ jobs:
 
   # STEP 5: Print the changelog outputs for debugging
   echo_changelog:
+    name: "Debug: Print changelog outputs"
+    if: false # This step is only for debugging purposes. It is not executed.
     runs-on: ubuntu-latest
     needs: changelog
     steps:
-      - name: "[DEBUG] Print changelog outputs"
+      - name: "Print changelog outputs"
+        env:
+          skipped: ${{ needs.changelog.outputs.skipped }}
+          tag: ${{ needs.changelog.outputs.tag }}
+          version: ${{ needs.changelog.outputs.version }}
         run: |
-          echo "[Changelog] Skipped - ${{ needs.changelog.outputs.skipped }}"
-          echo "[Changelog] Tag - ${{ needs.changelog.outputs.tag }}"
-          echo "[Changelog] Version - ${{ needs.changelog.outputs.version }}"
+          echo "## Changelog Outputs" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "[Changelog] Skipped - $skipped"  >> $GITHUB_STEP_SUMMARY
+          echo "[Changelog] Tag - $tag"  >> $GITHUB_STEP_SUMMARY
+          echo "[Changelog] Version - $version"  >> $GITHUB_STEP_SUMMARY
+          echo ""  >> $GITHUB_STEP_SUMMARY
 
   # STEP 6: Create a GitHub release with the changelog
   release:
@@ -169,3 +205,34 @@ jobs:
           generate_release_notes: true
           make_latest: "true"
           prerelease: false
+
+  # STEP 7: If the changelog step fails, rollback the changes
+  on-changelog-failure:
+    name: "Changelog: Failure"
+    if: failure()
+    needs: changelog
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
+        with:
+          fetch-depth: 0
+      - name: Delete Stale Branch
+        env:
+          BRANCH_NAME: ${{ needs.changelog.outputs.git_pr_branch }}
+        run: |
+          if ! [[ -z "$BRANCH_NAME" ]]; then
+            git push --quiet origin --delete $BRANCH_NAME
+            echo ""  >> $GITHUB_STEP_SUMMARY
+            echo "✅ Deleted '$BRANCH_NAME' branch." >> $GITHUB_STEP_SUMMARY
+          fi
+      - name: Delete Stale Tag
+        env:
+          TAG_VERSION: ${{ needs.changelog.outputs.tag }}
+        run: |
+          if git show-ref --tags --verify --quiet "refs/tags/$TAG_VERSION"; then
+            git push --delete origin $TAG_VERSION
+            echo ""  >> $GITHUB_STEP_SUMMARY
+            echo "✅ Deleted '$TAG_VERSION' tag." >> $GITHUB_STEP_SUMMARY
+            echo ""  >> $GITHUB_STEP_SUMMARY
+          fi
